/**
 * SOL — scene direction + planetary data.
 *
 * Every chapter owns one camera pose. Poses are expressed in the planet's
 * *own* orbital frame (inward / lateral / up), which means the camera rig can
 * be rebuilt every frame and will keep framing a world even while it orbits.
 *
 *   aim      : which body the camera frames ('sun' | planet id | 'system')
 *   back     : units behind the body, toward the Sun          (negative = outside)
 *   lat      : units along the orbit tangent
 *   up       : units above the ecliptic
 *   bias     : how far the body is pushed off-centre, in units of body radius
 *   fov      : vertical field of view for the chapter
 *   roll     : slight camera roll while the chapter is held (radians)
 */

export const SCENE = {
  sunRadius: 17,
  // distance compression: scene units for a body at `au` AU
  auToUnits: (au) => 84 * Math.pow(au, 0.45),
};

export const SUN = {
  id: 'sun',
  name: 'Sol',
  type: 'G2V main sequence',
  radius: SCENE.sunRadius,
  au: 0,
  color: '#ff9d3c',
  atmo: '#ffb45e',
};

export const CHAPTERS = [
  {
    id: 'hero',
    aim: 'system',
    kind: 'hero',
    name: 'Sol',
    kicker: ['real-time odyssey', '11 chapters'],
    title: ['SOL'],
    serif: false,
    au: 0,
    accent: '#ff9d3c',
    side: 'center',
    lede: 'One star, eight planets, four and a half billion years of momentum. <strong>Scroll to fall outward</strong> through the neighbourhood.',
    back: -430,
    lat: 60,
    up: 210,
    bias: 0,
    fov: 42,
    roll: -0.05,
    chips: ['procedural geometry', 'no video textures', 'webgl2 · gpu lit'],
  },
  {
    id: 'sun',
    aim: 'sun',
    kind: 'body',
    index: '01',
    name: 'The Star',
    eyebrow: 'the furnace',
    type: 'G2V · 4.6 Gyr',
    au: 0,
    accent: '#ff9d3c',
    side: 'left',
    body: 'sun',
    title: ['Sol'],
    lede: 'Every photon that has ever touched your skin began here — in a core fusing <strong>600 million tonnes of hydrogen a second</strong>, light that spent 100,000 years clawing its way out.',
    stats: [
      ['diameter', '1,392,700', 'km'],
      ['surface', '5,505', '°C'],
      ['core', '15,000,000', '°C'],
      ['spin', '25.4', 'days'],
    ],
    chips: ['99.86% of the system mass', 'flips its magnetic field every 11 years'],
    back: 74,
    lat: 26,
    up: 14,
    bias: 0.55,
    fov: 46,
    roll: 0.03,
  },
  {
    id: 'mercury',
    aim: 'mercury',
    kind: 'body',
    index: '02',
    name: 'Mercury',
    eyebrow: 'the scorched',
    type: 'terrestrial · no atmosphere',
    au: 0.387,
    accent: '#b3a492',
    side: 'right',
    body: 'mercury',
    title: ['Mercury'],
    lede: 'Locked in the Sun\'s gravity well, a Mercurian day outlasts its year: <strong>two orbits, one sunrise</strong>. Iron core, fried crust, and ice in polar craters that have never seen light.',
    stats: [
      ['distance', '0.39', 'AU'],
      ['diameter', '4,879', 'km'],
      ['solar day', '176', 'days'],
      ['moons', '0', ''],
    ],
    chips: ['smallest planet · smaller than Ganymede', '−173 °C to 427 °C'],
    back: 13,
    lat: -11,
    up: 5,
    bias: -0.52,
    fov: 42,
    roll: -0.04,
  },
  {
    id: 'venus',
    aim: 'venus',
    kind: 'body',
    index: '03',
    name: 'Venus',
    eyebrow: 'the runaway',
    type: 'terrestrial · 92 bar',
    au: 0.723,
    accent: '#e8c684',
    side: 'left',
    body: 'venus',
    title: ['Venus'],
    lede: 'The only world that turns backwards, wrapped in sulphuric cloud at <strong>ninety-two atmospheres</strong>. Hot enough to melt lead — and it has been raining for a billion years.',
    stats: [
      ['distance', '0.72', 'AU'],
      ['diameter', '12,104', 'km'],
      ['day', '243', 'days'],
      ['year', '224.7', 'days'],
    ],
    chips: ['retrograde rotation', '1,600 volcanoes · most in the system'],
    back: 16,
    lat: 13,
    up: -3.5,
    bias: 0.5,
    fov: 44,
    roll: 0.05,
  },
  {
    id: 'earth',
    aim: 'earth',
    kind: 'body',
    index: '04',
    name: 'Earth',
    eyebrow: 'the blue one',
    type: 'terrestrial · hydrosphere',
    au: 1,
    accent: '#6fb7ff',
    side: 'right',
    body: 'earth',
    title: ['Earth'],
    lede: 'A rock with liquid water, a magnetic shield, and a moon absurdly large for its parent — the only planet so far that <strong>knows it is a planet</strong>.',
    stats: [
      ['distance', '1.00', 'AU'],
      ['diameter', '12,742', 'km'],
      ['day', '23.93', 'hours'],
      ['moons', '1', ''],
    ],
    chips: ['71% ocean, 0% empty', 'atmosphere is 1% of its mass'],
    back: 15,
    lat: -13,
    up: 5,
    bias: -0.52,
    fov: 40,
    roll: -0.03,
  },
  {
    id: 'mars',
    aim: 'mars',
    kind: 'body',
    index: '05',
    name: 'Mars',
    eyebrow: 'the rusted',
    type: 'terrestrial · thin CO₂',
    au: 1.524,
    accent: '#e07a53',
    side: 'left',
    body: 'mars',
    title: ['Mars'],
    lede: 'A frozen desert wearing the tallest volcano and the deepest canyon in the system, carved by rivers that <strong>vanished before life found its footing</strong>.',
    stats: [
      ['distance', '1.52', 'AU'],
      ['diameter', '6,779', 'km'],
      ['day', '24.62', 'hours'],
      ['moons', '2', ''],
    ],
    chips: ['Olympus Mons: 22 km tall', 'dust storms that swallow the planet'],
    back: 13,
    lat: 10,
    up: -2.5,
    bias: 0.5,
    fov: 42,
    roll: 0.04,
  },
  {
    id: 'jupiter',
    aim: 'jupiter',
    kind: 'body',
    index: '06',
    name: 'Jupiter',
    eyebrow: 'the giant',
    type: 'gas giant · 318 Earths',
    au: 5.203,
    accent: '#dfa76e',
    side: 'right',
    body: 'jupiter',
    title: ['Jupiter'],
    lede: 'A failed star and a continent-sized storm; its bands shear at <strong>supersonic speed</strong>, and its magnetosphere would outshine the night sky of Earth if you could see it.',
    stats: [
      ['distance', '5.20', 'AU'],
      ['diameter', '139,820', 'km'],
      ['day', '9.93', 'hours'],
      ['moons', '95', ''],
    ],
    chips: ['Great Red Spot: 350 years of weather', '4 Galilean moons, one with a subsurface ocean'],
    back: 34,
    lat: -28,
    up: 10,
    bias: -0.54,
    fov: 48,
    roll: -0.06,
  },
  {
    id: 'saturn',
    aim: 'saturn',
    kind: 'body',
    index: '07',
    name: 'Saturn',
    eyebrow: 'the ringed',
    type: 'gas giant · ring system',
    au: 9.537,
    accent: '#eed9a4',
    side: 'left',
    body: 'saturn',
    title: ['Saturn'],
    lede: 'Ten billion trillion tonnes of water ice, ground to dust, in a disc <strong>ten metres thick</strong> and two hundred thousand wide. It is less structure than horizon.',
    stats: [
      ['distance', '9.54', 'AU'],
      ['diameter', '116,460', 'km'],
      ['rings', '282,000', 'km'],
      ['moons', '146', ''],
    ],
    chips: ['density 0.687 — it would float', 'rings may be only 100 Myr old'],
    back: 26,
    lat: 20,
    up: 13,
    bias: 0.5,
    fov: 46,
    roll: 0.06,
  },
  {
    id: 'uranus',
    aim: 'uranus',
    kind: 'body',
    index: '08',
    name: 'Uranus',
    eyebrow: 'the tilted',
    type: 'ice giant · 98° tilt',
    au: 19.191,
    accent: '#8fe3e0',
    side: 'right',
    body: 'uranus',
    title: ['Uranus'],
    lede: 'Knocked onto its side by an ancient impact, it rolls around the Sun — <strong>twenty-one years of daylight, twenty-one of night</strong>, at each pole in turn.',
    stats: [
      ['distance', '19.2', 'AU'],
      ['diameter', '50,724', 'km'],
      ['tilt', '97.8', '°'],
      ['moons', '28', ''],
    ],
    chips: ['coldest measured atmosphere: −224 °C', '13 faint, vertical rings'],
    back: 20,
    lat: -15,
    up: -8,
    bias: -0.5,
    fov: 44,
    roll: -0.05,
  },
  {
    id: 'neptune',
    aim: 'neptune',
    kind: 'body',
    index: '09',
    name: 'Neptune',
    eyebrow: 'the windy',
    type: 'ice giant · 2,100 km/h',
    au: 30.07,
    accent: '#6b8cff',
    side: 'left',
    body: 'neptune',
    title: ['Neptune'],
    lede: 'Found by mathematics before anyone pointed a lens at it — and still the fastest weather in the system: <strong>supersonic winds</strong> at the edge of the known.',
    stats: [
      ['distance', '30.1', 'AU'],
      ['diameter', '49,244', 'km'],
      ['year', '164.8', 'years'],
      ['moons', '16', ''],
    ],
    chips: ['one full season since discovery', 'Triton orbits backwards, and is freezing'],
    back: 22,
    lat: 16,
    up: 8,
    bias: 0.52,
    fov: 44,
    roll: 0.04,
  },
  {
    id: 'outro',
    aim: 'system',
    kind: 'outro',
    index: '10',
    name: 'The Long Dark',
    eyebrow: 'beyond neptune',
    accent: '#9aa4ff',
    side: 'center',
    au: 39.5,
    title: ['Kuiper'],
    serifWord: 'belt',
    lede: 'Past the last planet: two hundred billion icy bodies, one dwarf with nitrogen glaciers, and a boundary the Sun reaches only by gravity. <strong>Light needs five hours</strong> to get here.',
    chips: ['Pluto · Haumea · Makemake · Eris', 'Voyager 1: 48 years and still calling'],
    back: -540,
    lat: -120,
    up: 340,
    bias: 0,
    fov: 40,
    roll: 0.02,
  },
];

/** Planetary bodies, in orbital order. Sizes are art-compressed, not to scale. */
export const BODIES = [
  {
    id: 'mercury',
    name: 'Mercury',
    au: 0.387,
    radius: 1.28,
    color: '#9c9184',
    atmo: '#5d564e',
    atmoStrength: 0.08,
    tex: { kind: 'rocky', seed: 11, palette: ['#585047', '#7d746a', '#9a9084', '#3f3933', '#b3a99a'] },
    tilt: 0.0005,
    spin: 0.012,
    orbitSpeed: 0.032,
    phase: 0.6,
    craters: 780,
    rough: 0.94,
    moons: [],
  },
  {
    id: 'venus',
    name: 'Venus',
    au: 0.723,
    radius: 1.7,
    color: '#d8bb7f',
    atmo: '#ffd98a',
    atmoStrength: 0.55,
    tex: { kind: 'swirl', seed: 27, palette: ['#c8a468', '#e6d2a6', '#f5e8c8', '#a6834c', '#fffaea'] },
    tilt: 0.046,
    spin: -0.004,
    orbitSpeed: 0.024,
    phase: 2.15,
    rough: 0.72,
    clouds: { alpha: 'venus', color: '#fdf3d8', speed: 0.05, size: 1.02 },
    moons: [],
  },
  {
    id: 'earth',
    name: 'Earth',
    au: 1,
    radius: 1.78,
    color: '#2f6ba8',
    atmo: '#78b9ff',
    atmoStrength: 0.75,
    tex: { kind: 'earth', seed: 4, palette: ['#0a2c4c', '#13588c', '#41663c', '#8a7a4e', '#e8eef2'] },
    tilt: 0.409,
    spin: 0.06,
    orbitSpeed: 0.02,
    phase: 3.95,
    rough: 0.55,
    night: true,
    ocean: true,
    clouds: { alpha: 'earth', color: '#ffffff', speed: 0.026, size: 1.025 },
    moons: [{ id: 'moon', radius: 0.46, dist: 5.4, speed: 0.5, seed: 8, color: '#9c968c' }],
  },
  {
    id: 'mars',
    name: 'Mars',
    au: 1.524,
    radius: 1.34,
    color: '#b4553a',
    atmo: '#ff9d6b',
    atmoStrength: 0.22,
    tex: { kind: 'mars', seed: 19, palette: ['#7d3f2c', '#b56a45', '#d08d5f', '#5c3527', '#e8dccf'] },
    tilt: 0.44,
    spin: 0.058,
    orbitSpeed: 0.017,
    phase: 5.5,
    craters: 300,
    rough: 0.92,
    moons: [
      { id: 'phobos', radius: 0.14, dist: 2.9, speed: 1.3, seed: 3, color: '#8b7f74', lumpy: 0.5 },
      { id: 'deimos', radius: 0.1, dist: 4.1, speed: 0.85, seed: 6, color: '#847a70', lumpy: 0.6 },
    ],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    au: 5.203,
    radius: 5.3,
    color: '#c99a6b',
    atmo: '#ffd7a8',
    atmoStrength: 0.3,
    tex: { kind: 'bands', seed: 33, palette: ['#8a6440', '#d8b58c', '#f3e6d0', '#63432e', '#c37c52'], bands: 15, softness: 0.44, spot: true },
    tilt: 0.055,
    spin: 0.18,
    orbitSpeed: 0.008,
    phase: 1.15,
    rough: 0.62,
    moons: [
      { id: 'io', radius: 0.3, dist: 8.2, speed: 0.6, seed: 2, color: '#d8c46a' },
      { id: 'europa', radius: 0.26, dist: 10.6, speed: 0.46, seed: 5, color: '#d9cfc0' },
      { id: 'ganymede', radius: 0.38, dist: 13.4, speed: 0.34, seed: 9, color: '#9c8f81' },
      { id: 'callisto', radius: 0.35, dist: 17.2, speed: 0.24, seed: 13, color: '#7c7166' },
    ],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    au: 9.537,
    radius: 4.5,
    color: '#d9c391',
    atmo: '#ffeec4',
    atmoStrength: 0.24,
    tex: { kind: 'bands', seed: 47, palette: ['#b09566', '#e2cfa8', '#f7f0dc', '#8a7350', '#d3bb90'], bands: 12, softness: 0.5 },
    tilt: 0.466,
    spin: 0.16,
    orbitSpeed: 0.0055,
    phase: 4.6,
    rough: 0.66,
    rings: { inner: 1.32, outer: 2.32, tilt: 0, opacity: 1, tex: 'saturn' },
    moons: [
      { id: 'titan', radius: 0.34, dist: 15.4, speed: 0.3, seed: 21, color: '#d79a4e', atmo: '#ffb066' },
      { id: 'rhea', radius: 0.16, dist: 10.4, speed: 0.52, seed: 17, color: '#c9c6bf' },
    ],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    au: 19.191,
    radius: 3.15,
    color: '#8fd4d4',
    atmo: '#b6f3ee',
    atmoStrength: 0.34,
    tex: { kind: 'ice', seed: 61, palette: ['#74c2c6', '#a8e2df', '#daf6f1', '#5da4ac'], bands: 8, softness: 0.85 },
    tilt: 1.706,
    spin: -0.07,
    orbitSpeed: 0.0034,
    phase: 0.35,
    rough: 0.4,
    rings: { inner: 1.6, outer: 2.0, opacity: 0.42, tex: 'uranus' },
    moons: [
      { id: 'titania', radius: 0.18, dist: 8.4, speed: 0.4, seed: 31, color: '#b7b2ae' },
      { id: 'oberon', radius: 0.16, dist: 10.6, speed: 0.3, seed: 37, color: '#a49f9b' },
    ],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    au: 30.07,
    radius: 3.05,
    color: '#3f63d6',
    atmo: '#7f9dff',
    atmoStrength: 0.5,
    tex: { kind: 'ice', seed: 71, palette: ['#29479f', '#4a76d4', '#9cbcf3', '#1a2f75'], bands: 9, softness: 0.8, spot: '#12224d' },
    tilt: 0.494,
    spin: 0.08,
    orbitSpeed: 0.0026,
    phase: 2.9,
    rough: 0.42,
    clouds: { alpha: 'neptune', color: '#eaf1ff', speed: 0.04, size: 1.02 },
    moons: [{ id: 'triton', radius: 0.24, dist: 7.2, speed: -0.34, seed: 41, color: '#c6ccc9' }],
  },
];

/** Asteroid + Kuiper belts: [innerRadiusUnits, outerRadiusUnits, count, size] */
export const BELTS = [
  { id: 'main', from: 120, to: 152, count: 2400, size: 0.5, color: '#8d8175', speed: 0.012 },
  { id: 'kuiper', from: 408, to: 545, count: 5200, size: 1.1, color: '#6d7ba0', speed: 0.004 },
];
